#model
backbone: GIGA,CONCH,CHIEF,UNI,LUNIT,VIRCHOW,HOPT,ENLIGHT
model: MABMIL
D_inner: 1024
n_class: 2
#ckpt
ckpt_classifier: classifier/gbm-lgg_f1.ckpt
ckpt_lmm: enlight-fm
#data
cancer_prob_thresh: 0
classify_classes: GBM,LGG